import catalog from "./font-catalog.json"

/** One family served from this origin, as listed in lib/font-catalog.json. */
export interface FontCatalogEntry {
  /** Fontsource id, also the path segment under /fonts/. */
  id: string
  family: string
  category: string
  /** Variant names as the picker shows them: "regular", "italic", "700", "700italic". */
  variants: string[]
}

export interface FontCatalogPayload {
  fonts: FontCatalogEntry[]
}

/**
 * Generated by scripts/build-fonts.ts from the Fontsource packages named in
 * fonts/families.json. Every family here has a stylesheet at /fonts/<id>.css
 * and its files under /fonts/<id>/, so no font ever loads from a third party.
 */
export const fontCatalog: FontCatalogPayload = catalog
